# Generated by Django 4.2.2 on 2023-06-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_genero', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genero',
                'ordering': ['tipo_genero'],
            },
        ),
    ]
