# Generated by Django 4.2.2 on 2023-06-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_livro', models.CharField(max_length=100)),
                ('nome_autor', models.CharField(max_length=75)),
                ('numero_paginas', models.IntegerField(blank=True, null=True)),
                ('ano_publicacao', models.IntegerField(default=2023)),
                ('localizacao', models.CharField(max_length=3)),
                ('categoria', models.CharField(max_length=10)),
                ('genero', models.ManyToManyField(to='home.genero')),
            ],
        ),
    ]
