# Generated by Django 4.2.2 on 2023-06-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_livro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['titulo_livro']},
        ),
        migrations.AlterModelTable(
            name='livro',
            table='livro',
        ),
    ]
