# Generated by Django 4.2.2 on 2023-06-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_livro_options_alter_livro_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='ano_publicacao',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='numero_paginas',
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
