# Generated by Django 4.2.2 on 2023-06-21 16:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_livro_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=datetime.date(2023, 6, 21)),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='prazo_devolucao',
            field=models.DateField(default=datetime.date(2023, 8, 22)),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nome_completo', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=255)),
                ('telefone', models.CharField(max_length=12)),
                ('dependentes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.usuario')),
            ],
        ),
    ]
