# Generated by Django 4.2.2 on 2023-06-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_emprestimo_data_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='fk_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='home.usuario'),
        ),
    ]
