# Generated by Django 4.2.2 on 2023-06-21 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_emprestimo_fk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='fk_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.usuario'),
        ),
    ]
